language: php

php:
  - 7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - cp .env.travis .env
  - php artisan key:generate

script: phpunit
